In [1]:
from circuitClass import *

## The circuit That I try to Solve
In this document, I am trying to see if my code can generate the right equations for the following circuit.
<img src="pic/pic4.png" style="height:250px">

## Define the circuit for the circuitClass 
In this part, I define the input which is necessery for the Hamiltonian.

In [2]:
graph = [[0,1],[0,2],[1,2],[1,3],[2,5],[2,6],[6,5],[3,5],[3,4],[4,5]]
L = [1,0,0,1,0,1,0,0,1,0]
C = [1,1,1,1,1,1,1,1,1,1]
JJ = [0,1,1,0,[1,1],0,1,1,0,1]
phi = np.linspace(0,0.5,15)*2*np.pi

# define the circuit
cr1 = Qcircuit(graph,L,C,JJ)
excite = [([0,1,2],0),([1, 3, 5, 2],0),([2, 6, 5],0),([3, 4, 5],0),([2,5],10)]
cr1.setExcitation(excite)
cr1.configure()
print(cr1.omega)

[0 0 1 0 0 0 1 1 0 1]
[False  True  True False  True False  True  True False  True]
[0.88650607 0.80946812 0.6962717  0.79349205 0.         0.        ]


In [4]:
print(cr1.graphSt.simplestCycles)

[[0, 2, 1], [1, 3, 5, 2], [2, 6, 5], [3, 4, 5]]


In [5]:
cr1.JJExcite

[[0], [1, 0], [2], [3, 1, 0], 0, [0, 4]]

In [6]:
lRotated, cInvRotated , S = cr1.buildDiag()
print("lRotated:")
print(np.diag(lRotated))
# print("cInvRotated:")
# print(cInvRotated)
print("S:")
print(S)
print("JJEq@S:")
print(cr1.JJEq @S)

lRotated:
[3.2469796  1.55495813 0.19806226 2.         0.         0.        ]
S:
[[-0.59100905 -0.73697623  0.32798528  0.          0.          0.        ]
 [ 0.          0.          0.          0.70710678  0.70710678  0.        ]
 [ 0.73697623 -0.32798528  0.59100905  0.          0.          0.        ]
 [-0.32798528  0.59100905  0.73697623  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.        ]
 [ 0.          0.          0.         -0.70710678  0.70710678  0.        ]]
JJEq@S:
[[-0.59100905 -0.73697623  0.32798528  0.70710678  0.70710678  0.        ]
 [ 0.73697623 -0.32798528  0.59100905  0.          0.          1.        ]
 [ 0.          0.          0.         -2.12132034 -0.70710678  1.        ]
 [-0.32798528  0.59100905  0.73697623  0.          0.          1.        ]
 [ 0.          0.          0.          0.70710678  0.70710678  0.        ]
 [ 0.          0.          0.          0.70710678  0.70710678 -1.        ]]


In [6]:
cr1.JJExcite

[[0], [[1, 0], 5], [2], [3, 1, 0], 0, [0, 4]]

# another circuit
<img src="pic/pic5.png" style="height:250px">

In [7]:
graph = [[0,1],[0,2],[1,2],[1,3],[2,4],[3,4]]
L = [1,0,0,1,0,0]
C = [1,1,1,1,1,1]
JJ = [0,1,1,0,1,1]
phi = np.linspace(0,0.5,15)*2*np.pi

# define the circuit
cr2 = Qcircuit(graph,L,C,JJ,phi)
cr2.configure()

In [8]:
print(np.array(cr2.JJEq))

[[ 1.  1.  0.  0.]
 [ 0.  0.  1.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0. -1.]]


In [9]:
lRotated, cInvRotated , S = cr2.buildDiag()
print("lRotated:")
print(np.diag(lRotated))
# print("cInvRotated:")
# print(cInvRotated)
print("S:")
print(S)
print("JJEq@S:")
print(np.array(cr2.JJEq) @S)

lRotated:
[2.61803399 0.38196601 0.         0.        ]
S:
[[ 0.85065081  0.52573111  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [-0.52573111  0.85065081  0.          0.        ]
 [ 0.          0.          0.          1.        ]]
JJEq@S:
[[ 0.85065081  0.52573111  1.          0.        ]
 [-0.52573111  0.85065081  0.          1.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          1.         -1.        ]]


In [10]:
c = q.num(3)

In [11]:
c*c

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 4.]]

In [12]:
q.Qobj(np.ones((10,10)))

Quantum object: dims = [[10], [10]], shape = (10, 10), type = oper, isherm = True
Qobj data =
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

In [13]:
m = 2
A = np.zeros((m,m))
for i in range(m):
    for j in range(m):
        if(j-1==i):
            A[i,j] = 1;
A = q.Qobj(A)
A

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 1.]
 [0. 0.]]

In [43]:
a = q.basis(2,1)
a

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [45]:
np.array([1,2,None])

array([1, 2, None], dtype=object)

In [18]:
a = np.linspace(1,5,5)
b = [0,0,0,a]
b
print(isinstance(b[3],int))

False
