In [1]:
from circuitClass import *

## The circuit That I try to Solve
In this document, I am trying to see if my code can generate the right equations for the following circuit.
<img src="pic/pic4.png" style="height:250px">

## Define the circuit for the circuitClass 
In this part, I define the input which is necessery for the Hamiltonian.

In [2]:
graph = [[0,1],[0,2],[1,2],[1,3],[2,5],[2,6],[6,5],[3,5],[3,4],[4,5]]
L = [1,0,0,1,0,1,0,0,1,0]
C = [1,1,1,1,1,1,1,1,1,1]
JJ = [0,1,1,0,[1,1],0,1,1,0,1]
phi = np.linspace(0,0.5,15)*2*np.pi

# define the circuit
cr1 = Qcircuit(graph,L,C,JJ,phi)

In [3]:
cycles = cr1.findAllCycles();
simplestCycles = cr1.giveSimplestCycles(cycles);

In [4]:
for cy in simplestCycles:
    path = [str(node) for node in cy];
    s = "-".join(path);
    print(s)

0-2-1
1-3-5-2
2-6-5
3-4-5


In [5]:
spanningTrees = cr1.findSpanningTrees()
# for tree in spanningTrees:
#     print(tree)
    
spanTree = cr1.giveMaxInd()
tree = spanTree.copy();
treeWithDirec = cr1.treeDirec(0,None,[],tree)
print("spanning tree with direction:",treeWithDirec)
O, notInSpan = cr1.cycleEqu(simplestCycles,treeWithDirec)

print(notInSpan)
print(O)

spanning tree with direction: [[0, 1], [1, 3], [3, 4], [0, 2], [2, 5], [2, 6]]
[[[2, 1]], [[2, 1], [3, 5]], [[6, 5]], [[5, 3], [4, 5]]]
[[1, 1, 0, 0, 0, 0], [-1, -1, 1, 0, 1, 0], [0, -2, 0, 0, 1, 1], [0, 0, -1, 1, 0, 0]]


In [6]:
JJEj , JJEq , JJExcite = cr1.giveJJEq(O,notInSpan)

[[2, 1], [3, 5], [6, 5], [5, 3], [4, 5]]
[0, 0, 1, 0, 0, 0, 1, 1, 0, 1]
[0, 1, 0, 0, 1, 0, 0, 0, 0, 0]


In [8]:
lRotated, cInvRotated , S = cr1.buildDiag()
print("lRotated:")
print(lRotated)
print("cInvRotated:")
print(cInvRotated)
print("S:")
print(S)

lRotated:
[[ 3.24697960e+00  6.66133815e-16 -4.44089210e-16  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 6.66133815e-16  1.55495813e+00  2.22044605e-16  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.99600361e-16  2.35922393e-16  1.98062264e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
cInvRotated:
[[ 0.24203817  0.01179641  0.01170967 -0.01877681 -0.02947371  0.01899058]
 [ 0.01179641  0.42138667 -0.09758015 -0.02373071 -0.1522312  -0.05730327]
 [ 0.01170967 -0.09758015  2.44768627 -0.1670056   1.28164879  1.26053492]
 [-0.01877681 -0.02373071 -0.1670056   0.31481481 -0.27777778 -0.15713484]
 [-0.02947371 -0.1522312   1.28164879 -0.27777778  1.5         0.94280

In [33]:
A = np.array([[0,1,0],[0,0,1],[0,0,0]])
B = np.array([[0,0,0],[1,0,0],[0,1,0]])
print(A@B)
print(B@A)

[[1 0 0]
 [0 1 0]
 [0 0 0]]
[[0 0 0]
 [0 1 0]
 [0 0 1]]


In [39]:
JJ= [1, [1,0], 0 ,1]
x = np.array(JJ).astype(bool)
i=0
while( False in x):
    print(x[i])
    x[i] = True
    i+=1

True
True
False


In [17]:
a = [1,2,3]
print(set(a))

{1, 2, 3}
