In [1]:
from circuitClass import *

## The circuit That I try to Solve
In this document, I am trying to see if my code can generate the right equations for the following circuit.
<img src="pic/pic4.png" style="height:250px">

## Define the circuit for the circuitClass 
In this part, I define the input which is necessery for the Hamiltonian.

In [2]:
graph = [[0,1],[0,2],[1,2],[1,3],[2,5],[2,6],[6,5],[3,5],[3,4],[4,5]]
L = [1,0,0,1,0,1,0,0,1,0]
C = [1,1,1,1,1,1,1,1,1,1]
JJ = [0,1,1,0,[1,1],0,1,1,0,1]
phi = np.linspace(0,0.5,15)*2*np.pi

# define the circuit
cr1 = Qcircuit(graph,L,C,JJ,phi)
cr1.configure()

In [5]:
print(np.array(cr1.JJEq))

[[ 1.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  1.  0.]
 [ 0. -2.  0.  0.  1.  1.]
 [ 0.  0.  0.  1.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.  0.]]


In [7]:
lRotated, cInvRotated , S = cr1.buildDiag()
print("lRotated:")
print(np.diag(lRotated))
# print("cInvRotated:")
# print(cInvRotated)
print("S:")
print(S)
print("JJEq@S:")
print(cr1.JJEq @S)

lRotated:
[3.2469796  1.55495813 0.19806226 2.         0.         0.        ]
S:
[[-0.59100905 -0.73697623  0.32798528  0.          0.          0.        ]
 [ 0.          0.          0.          0.70710678  0.70710678  0.        ]
 [ 0.73697623 -0.32798528  0.59100905  0.          0.          0.        ]
 [-0.32798528  0.59100905  0.73697623  0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.        ]
 [ 0.          0.          0.         -0.70710678  0.70710678  0.        ]]
JJEj@S:
[[-0.59100905 -0.73697623  0.32798528  0.70710678  0.70710678  0.        ]
 [ 0.73697623 -0.32798528  0.59100905  0.          0.          1.        ]
 [ 0.          0.          0.         -2.12132034 -0.70710678  1.        ]
 [-0.32798528  0.59100905  0.73697623  0.          0.          1.        ]
 [ 0.          0.          0.          0.70710678  0.70710678  0.        ]
 [ 0.          0.          0.          0.70710678  0.70710678 -1.        ]]


# another circuit
<img src="pic/pic5.png" style="height:250px">

In [9]:
graph = [[0,1],[0,2],[1,2],[1,3],[2,4],[3,4]]
L = [1,0,0,1,0,0]
C = [1,1,1,1,1,1]
JJ = [0,1,1,0,1,1]
phi = np.linspace(0,0.5,15)*2*np.pi

# define the circuit
cr2 = Qcircuit(graph,L,C,JJ,phi)
cr2.configure()

In [12]:
print(np.array(cr2.JJEq))

[[ 1.  1.  0.  0.]
 [ 0.  0.  1.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0. -1.]]


In [17]:
lRotated, cInvRotated , S = cr2.buildDiag()
print("lRotated:")
print(np.diag(lRotated))
# print("cInvRotated:")
# print(cInvRotated)
print("S:")
print(S)
print("JJEq@S:")
print(np.array(cr2.JJEq) @S)

lRotated:
[2.61803399 0.38196601 0.         0.        ]
S:
[[ 0.85065081  0.52573111  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [-0.52573111  0.85065081  0.          0.        ]
 [ 0.          0.          0.          1.        ]]
JJEq@S:
[[ 0.85065081  0.52573111  1.          0.        ]
 [-0.52573111  0.85065081  0.          1.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          1.         -1.        ]]
